# Generated by Django 4.2.1 on 2023-05-18 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_book_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Novel', 'Novel'), ('Poetry', 'Poetry'), ('Drama', 'Drama'), ('Non-fiction', 'Non-fiction'), ('Scientific literature', 'Scientific literature'), ('Fantasy', 'Fantasy'), ('Crime fiction', 'Crime fiction'), ('Romance', 'Romance'), ('Horror', 'Horror'), ("Children's and Young Adult literature", "Children's and Young Adult literature"), ('other', 'other')], max_length=50),
        ),
    ]
