# Generated by Django 4.2.1 on 2023-05-19 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_borrower_books_loan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books_loan',
            name='end_loan',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='books_loan',
            name='start_loan',
            field=models.DateField(auto_now_add=True),
        ),
    ]
